// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOaIfkLg15PjRkVV-mK-jV80Gi8FvxF9g',
    appId: '1:1071653908052:web:c0c177cf22727b24a947c1',
    messagingSenderId: '1071653908052',
    projectId: 'cleon-mobile-deep-link',
    authDomain: 'cleon-mobile-deep-link.firebaseapp.com',
    storageBucket: 'cleon-mobile-deep-link.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1s_-s5sTt1DBtkbspwEoeuveuWQvQzMY',
    appId: '1:1071653908052:android:9ddf727452f31627a947c1',
    messagingSenderId: '1071653908052',
    projectId: 'cleon-mobile-deep-link',
    storageBucket: 'cleon-mobile-deep-link.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt3V_CizIONlfTHUsxY8gEfb-ytom12ao',
    appId: '1:1071653908052:ios:f45571c4c2a06035a947c1',
    messagingSenderId: '1071653908052',
    projectId: 'cleon-mobile-deep-link',
    storageBucket: 'cleon-mobile-deep-link.appspot.com',
    androidClientId: '1071653908052-ur785kpi0v4vuj0a0aiq6903smlb9a58.apps.googleusercontent.com',
    iosClientId: '1071653908052-8ooecgfveennvrguokvb0q1dkcjk6qep.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
